### ISSUE TITLE
Support for streaming data

### ISSUE THREAD

**Issue by blackvvine** [williamleif/GraphSAGE#149]
Hello,

I would like to use GraphSAGE on a massive streaming graph where I'm receiving new nodes and edges on, say, a Kafka queue. We want to generate the node embedding on the fly as data flows in.

Is there anyway to integrate GraphSAGE to be used on a stream of edges as opposed to a fixed dataset, in such a set-up?

**Comment by sam-lev** [comment]
graphsage doesn’t account for online learning but you would be able to train on the graph you currently have, apply a downstream approach such as linear regression for classification and then re-train to learn a more developed embedding.  Another similar approach would be to use pinsage which is oriented to a more dynamic graph setting and allows for training new embeddings with a learned model [pinsage](https://scholar.google.com/scholar?q=graphsage+pinterest+graph+neural+network+pinsage&hl=en&as_sdt=0&as_vis=1&oi=scholart#d=gs_qabs&u=%23p%3DnjZcFky1ixYJ)  but again this is offline.

**Comment by blackvvine** [comment]
I see, thank you. Follow-up question:
- Doesn't the fact that GraphSAGE is inductive make it possible to apply a trained model to the new nodes, similar to what you just described? An "approximate" online embedding for the new nodes is fine for us, since we need some node representation to use for the time between the GraphSAGE re-trainings and we're working with millions of nodes.
- Are you aware of any online graph embedding solutions?

**Comment by sam-lev** [comment]
-  Yes, graphsage being inductive is one of it's strong suits so can be easily re-trained (on an extension of the original training graph) or re-trained easily on similar graph. An example would be a training on a subgraph/clique representitive of the graph and extending the trained model to the full graph or training on a graph which in time will 'grow'. Even though I'm unsure of your full problem setting it seems it might be sufficient to train on whatever subset you have, use the trained embedding for a 'downstream' learning approach like linear regression which is provided in the graphsage repo's 'eval scripts' and during the interem where you use inference through downstream methods you also re-train a more robust model assuming you have some sort of labeling scheme where predictions from inference are not being used as labels for training a supervised model. Applying graphsage to entirely new graphs, since it is inductive, is also possible and definitely when using a trained embedding in a more gradient based type regression however a problem I am currently working on and haven't been able to resolve is using a trained network/ aggregator functions to extend to entirely new graphs of similar topology for inference so if you're facing a situation beyond a graph growing in scale this might be a hiccup. Also, noting the scale you mentioned I would strongly consider Pinsage which is used for Pintrest and largely designed with the intent of a large scale and growing graph.
- As for purely online graph embedding techniques I don't know any of the top of my head and don't want to speak before thinking but it is an interesting question so if I find anything relevant as I look into it I'll post again here or message.

**Comment by blackvvine** [comment]
Unfortunately the PinSage repositories I've seen so far are not very mature, so we'll probably have no choice but the periodic retraining. Thank you for the information.
