### ISSUE TITLE
Is f1_score evaluation wrong in ppi_eval.py?

### ISSUE THREAD

**Issue by happylicio** [williamleif/GraphSAGE#16]
https://github.com/williamleif/GraphSAGE/blob/da7b91464abaa458248a4b29b3cce50873bfffdc/eval_scripts/ppi_eval.py#L28

In ppi_eval.py,  your f1_score evaluation seems wired which is different from your implementations in citation_eval.py and reddit_eval.py.  According to my understanding,  `test_labels ` and `log.predict(test_embeds)` are of the shape [batch_size(5124), num_classes(121)],  so you actually calculate the per-class f1_score. Does this satisfy your expectation and why?

**Comment by williamleif** [comment]
Hi,

Thanks for the question! We opted to do a per-class F1-score for the ppi data because it is a multi-label classification problem (i.e., a single datapoint can belong to multiple classes). In contrast, the other datasets are multi-class predictions but each datapoint can only belong to exactly one class. This is also why the "--sigmoid" flag needs to be set when using the PPI data, but not for the other datasets. However, I realize now that this could be made more clear, and we will add more detail on this in the appendix in future revisions of our paper.

Best,
Will
